class Entity :
    Name=''
    EmailID=''
    PhoneNumber=''
    Location=''
    Organization=''
    Designation=''
    Duration=''
    Project1=''
    Project2=''
    Skills=''
    Qualifications=''
    Collage=''
    G_year=''
    Excperience=''

    def __init__(self,Name,
    EmailID,
    PhoneNumber,
    Location,
    Organization,
    Designation,
    Duration,
    Project1,
    Project2,
    Skills,
    Qualifications,
    Collage,
    G_year,
    Excperience):
        self.Name=Name
        self.EmailID=EmailID
        self.PhoneNumber=PhoneNumber
        self.Location=Location
        self.Organization=Organization
        self.Designation=Designation
        self.Duration=Duration
        self.Project1=Project1
        self.Project2=Project2
        self.Skills=Skills
        self.Qualifications=Qualifications
        self.Collage=Collage
        self.G_year=G_year
        self.Excperience=Excperience